# .github/workflows/hello-world.yml
name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false   
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"