# .github/workflows/pr_event.yml
name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print PR info
        run: |
          echo "Pull Request triggered"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Branch: ${{ github.head_ref }}"